/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Igu;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import proyecto.aula.Usuario;


/**
 *
 * @author Usuario
 */
public class Pantalla extends javax.swing.JFrame {
   
  
    public Pantalla() {
        
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        barramenu = new javax.swing.JMenuBar();
        menuUsuarios = new javax.swing.JMenu();
        itemAgregarUsuario = new javax.swing.JMenuItem();
        itemConsultarUsuario = new javax.swing.JMenuItem();
        itemEditarUsuario = new javax.swing.JMenuItem();
        subMenuReporteUsuarios = new javax.swing.JMenu();
        itemTodosLosUsuarios1 = new javax.swing.JMenuItem();
        itemBuscarUsuarioXTelefono = new javax.swing.JMenuItem();
        itemBuscarServicioXValor1 = new javax.swing.JMenuItem();
        itemBuscarServicioXEmail = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("..:GESTION DE SERVICIOS:..");
        setBackground(new java.awt.Color(0, 0, 0));
        setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Igu/Iconos/usuario252px.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 220, 270));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Igu/Iconos/report256px.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 170, -1, -1));

        jButton1.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jButton1.setText("Reportes de usuarios");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 430, 280, -1));

        jButton2.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jButton2.setText("Agregar usuario");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 220, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Igu/Iconos/FONDO.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 680));

        barramenu.setBackground(new java.awt.Color(0, 0, 0));

        menuUsuarios.setBackground(new java.awt.Color(0, 0, 0));
        menuUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        menuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Igu/iconos/usuario24px.png"))); // NOI18N
        menuUsuarios.setText("Usuarios");
        menuUsuarios.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        itemAgregarUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        itemAgregarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Igu/Iconos/add24px.png"))); // NOI18N
        itemAgregarUsuario.setText("Agregar usuario..");
        itemAgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarUsuarioActionPerformed(evt);
            }
        });
        menuUsuarios.add(itemAgregarUsuario);

        itemConsultarUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        itemConsultarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Igu/iconos/buscar24px.png"))); // NOI18N
        itemConsultarUsuario.setText("Consultar datos..");
        itemConsultarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemConsultarUsuarioActionPerformed(evt);
            }
        });
        menuUsuarios.add(itemConsultarUsuario);

        itemEditarUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        itemEditarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Igu/iconos/edit24px.png"))); // NOI18N
        itemEditarUsuario.setText("Editar mis datos...");
        itemEditarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEditarUsuarioActionPerformed(evt);
            }
        });
        menuUsuarios.add(itemEditarUsuario);

        subMenuReporteUsuarios.setText("Reportes");
        subMenuReporteUsuarios.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        itemTodosLosUsuarios1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        itemTodosLosUsuarios1.setText("Todos...");
        itemTodosLosUsuarios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTodosLosUsuarios1ActionPerformed(evt);
            }
        });
        subMenuReporteUsuarios.add(itemTodosLosUsuarios1);

        itemBuscarUsuarioXTelefono.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        itemBuscarUsuarioXTelefono.setText("Por nombre...");
        subMenuReporteUsuarios.add(itemBuscarUsuarioXTelefono);

        itemBuscarServicioXValor1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        itemBuscarServicioXValor1.setText("Por telefono...");
        itemBuscarServicioXValor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBuscarServicioXValor1ActionPerformed(evt);
            }
        });
        subMenuReporteUsuarios.add(itemBuscarServicioXValor1);

        itemBuscarServicioXEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        itemBuscarServicioXEmail.setText("Por email...");
        itemBuscarServicioXEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBuscarServicioXEmailActionPerformed(evt);
            }
        });
        subMenuReporteUsuarios.add(itemBuscarServicioXEmail);

        menuUsuarios.add(subMenuReporteUsuarios);

        barramenu.add(menuUsuarios);

        setJMenuBar(barramenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemBuscarServicioXEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBuscarServicioXEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemBuscarServicioXEmailActionPerformed

    private void itemBuscarServicioXValor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBuscarServicioXValor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemBuscarServicioXValor1ActionPerformed

    private void itemTodosLosUsuarios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTodosLosUsuarios1ActionPerformed

        if(Usuario.usuarioBD == null || Usuario.usuarioBD.isEmpty()){
            JOptionPane.showMessageDialog(this, "No existen usuarios registrados"
            );
            return;
        }
        VentanaReportes ventana = new VentanaReportes();
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemTodosLosUsuarios1ActionPerformed

    private void itemEditarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEditarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemEditarUsuarioActionPerformed

    private void itemConsultarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemConsultarUsuarioActionPerformed

    }//GEN-LAST:event_itemConsultarUsuarioActionPerformed

    private void itemAgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarUsuarioActionPerformed
        PantallaUsuarios1 dialog = new PantallaUsuarios1();
                

        dialog.setVisible(true);
    }//GEN-LAST:event_itemAgregarUsuarioActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       PantallaUsuarios1 dialogo = new PantallaUsuarios1();

        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
               
        VentanaReportes ventana = new VentanaReportes();
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);        

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                
                new Pantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barramenu;
    private javax.swing.JMenuItem itemAgregarUsuario;
    private javax.swing.JMenuItem itemBuscarServicioXEmail;
    private javax.swing.JMenuItem itemBuscarServicioXValor1;
    private javax.swing.JMenuItem itemBuscarUsuarioXTelefono;
    private javax.swing.JMenuItem itemConsultarUsuario;
    private javax.swing.JMenuItem itemEditarUsuario;
    private javax.swing.JMenuItem itemTodosLosUsuarios1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuUsuarios;
    private javax.swing.JMenu subMenuReporteUsuarios;
    // End of variables declaration//GEN-END:variables
    
  
    
    
   
    
}
