/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Igu;

import javax.swing.JOptionPane;
import proyecto.aula.Usuario;

/**
 *
 * @author Usuario
 */
public class Pantalla extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barramenu = new javax.swing.JMenuBar();
        menuUsuarios = new javax.swing.JMenu();
        itemIniciarSesionUsuario = new javax.swing.JMenuItem();
        itemAgregarUsuario = new javax.swing.JMenuItem();
        itemConsultarUsuario = new javax.swing.JMenuItem();
        itemEditarUsuario = new javax.swing.JMenuItem();
        itemEliminarUsuario = new javax.swing.JMenuItem();
        subMenuReporteUsuarios = new javax.swing.JMenu();
        itemTodosLosUsuarios1 = new javax.swing.JMenuItem();
        itemBuscarUsuarioXTelefono = new javax.swing.JMenuItem();
        itemBuscarServicioXValor1 = new javax.swing.JMenuItem();
        itemBuscarServicioXEmail = new javax.swing.JMenuItem();
        MenuServicios = new javax.swing.JMenu();
        itemAgregarServicios = new javax.swing.JMenuItem();
        itemConsultarServicios = new javax.swing.JMenuItem();
        itemEditarServicios = new javax.swing.JMenuItem();
        itemEliminarServicios = new javax.swing.JMenuItem();
        itemEliminarServicios1 = new javax.swing.JMenuItem();
        itemEditarServicios1 = new javax.swing.JMenuItem();
        subMenuReporteServicios = new javax.swing.JMenu();
        itemTodosLosUsuarios = new javax.swing.JMenuItem();
        itemBuscarServicioXNombre = new javax.swing.JMenuItem();
        itemBuscarServicioXValor = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem16 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("..:GESTION DE SERVICIOS:..");
        setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        menuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Igu/iconos/usuario24px.png"))); // NOI18N
        menuUsuarios.setText("Usuarios");
        menuUsuarios.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        itemIniciarSesionUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        itemIniciarSesionUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Igu/iconos/login24px.png"))); // NOI18N
        itemIniciarSesionUsuario.setText("Inicio de sesión...");
        itemIniciarSesionUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemIniciarSesionUsuarioActionPerformed(evt);
            }
        });
        menuUsuarios.add(itemIniciarSesionUsuario);

        itemAgregarUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        itemAgregarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Igu/iconos/add24px.png"))); // NOI18N
        itemAgregarUsuario.setText("Agregar usuario..");
        itemAgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarUsuarioActionPerformed(evt);
            }
        });
        menuUsuarios.add(itemAgregarUsuario);

        itemConsultarUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        itemConsultarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Igu/iconos/buscar24px.png"))); // NOI18N
        itemConsultarUsuario.setText("Consultar datos..");
        itemConsultarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemConsultarUsuarioActionPerformed(evt);
            }
        });
        menuUsuarios.add(itemConsultarUsuario);

        itemEditarUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        itemEditarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Igu/iconos/edit24px.png"))); // NOI18N
        itemEditarUsuario.setText("Editar mis datos...");
        itemEditarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEditarUsuarioActionPerformed(evt);
            }
        });
        menuUsuarios.add(itemEditarUsuario);

        itemEliminarUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        itemEliminarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Igu/iconos/delete24px.png"))); // NOI18N
        itemEliminarUsuario.setText("Eliminar mis datos..");
        itemEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEliminarUsuarioActionPerformed(evt);
            }
        });
        menuUsuarios.add(itemEliminarUsuario);

        subMenuReporteUsuarios.setText("Reportes");
        subMenuReporteUsuarios.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        itemTodosLosUsuarios1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        itemTodosLosUsuarios1.setText("Todos...");
        itemTodosLosUsuarios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTodosLosUsuarios1ActionPerformed(evt);
            }
        });
        subMenuReporteUsuarios.add(itemTodosLosUsuarios1);

        itemBuscarUsuarioXTelefono.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        itemBuscarUsuarioXTelefono.setText("Por nombre...");
        subMenuReporteUsuarios.add(itemBuscarUsuarioXTelefono);

        itemBuscarServicioXValor1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        itemBuscarServicioXValor1.setText("Por telefono...");
        itemBuscarServicioXValor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBuscarServicioXValor1ActionPerformed(evt);
            }
        });
        subMenuReporteUsuarios.add(itemBuscarServicioXValor1);

        itemBuscarServicioXEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        itemBuscarServicioXEmail.setText("Por email...");
        itemBuscarServicioXEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBuscarServicioXEmailActionPerformed(evt);
            }
        });
        subMenuReporteUsuarios.add(itemBuscarServicioXEmail);

        menuUsuarios.add(subMenuReporteUsuarios);

        barramenu.add(menuUsuarios);

        MenuServicios.setText("Servicios");
        MenuServicios.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        itemAgregarServicios.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        itemAgregarServicios.setText("Agregar servicios..");
        itemAgregarServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarServiciosActionPerformed(evt);
            }
        });
        MenuServicios.add(itemAgregarServicios);

        itemConsultarServicios.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        itemConsultarServicios.setText("Consultar servicios..");
        itemConsultarServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemConsultarServiciosActionPerformed(evt);
            }
        });
        MenuServicios.add(itemConsultarServicios);

        itemEditarServicios.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        itemEditarServicios.setText("Editar servicios..");
        itemEditarServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEditarServiciosActionPerformed(evt);
            }
        });
        MenuServicios.add(itemEditarServicios);

        itemEliminarServicios.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        itemEliminarServicios.setText("Eliminar servicios...");
        itemEliminarServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEliminarServiciosActionPerformed(evt);
            }
        });
        MenuServicios.add(itemEliminarServicios);

        itemEliminarServicios1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        itemEliminarServicios1.setText("Eliminar servicios...");
        itemEliminarServicios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEliminarServicios1ActionPerformed(evt);
            }
        });
        MenuServicios.add(itemEliminarServicios1);

        itemEditarServicios1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        itemEditarServicios1.setText("Editar servicios..");
        itemEditarServicios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEditarServicios1ActionPerformed(evt);
            }
        });
        MenuServicios.add(itemEditarServicios1);

        subMenuReporteServicios.setText("Reportes");
        subMenuReporteServicios.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        itemTodosLosUsuarios.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        itemTodosLosUsuarios.setText("Todos...");
        subMenuReporteServicios.add(itemTodosLosUsuarios);

        itemBuscarServicioXNombre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        itemBuscarServicioXNombre.setText("Nombre...");
        subMenuReporteServicios.add(itemBuscarServicioXNombre);

        itemBuscarServicioXValor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        itemBuscarServicioXValor.setText("Valor...");
        subMenuReporteServicios.add(itemBuscarServicioXValor);

        MenuServicios.add(subMenuReporteServicios);

        barramenu.add(MenuServicios);

        jMenu3.setText("Ayuda");
        jMenu3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jMenuItem16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem16.setText("Acerca de...");
        jMenu3.add(jMenuItem16);

        barramenu.add(jMenu3);

        setJMenuBar(barramenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemIniciarSesionUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemIniciarSesionUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemIniciarSesionUsuarioActionPerformed

    private void itemAgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarUsuarioActionPerformed
    PantallaUsuarios pantalla = new PantallaUsuarios (this,true);   
    pantalla.setLocationRelativeTo(this);
    pantalla.setVisible(true);
    }//GEN-LAST:event_itemAgregarUsuarioActionPerformed

    private void itemConsultarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemConsultarUsuarioActionPerformed

       PantallaBusqueda pantalla2 = new PantallaBusqueda();
       pantalla2.setLocationRelativeTo(this);
       pantalla2.setVisible(true);
          
    }//GEN-LAST:event_itemConsultarUsuarioActionPerformed

    private void itemEditarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEditarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemEditarUsuarioActionPerformed

    private void itemEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEliminarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemEliminarUsuarioActionPerformed

    private void itemAgregarServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarServiciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemAgregarServiciosActionPerformed

    private void itemConsultarServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemConsultarServiciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemConsultarServiciosActionPerformed

    private void itemEditarServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEditarServiciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemEditarServiciosActionPerformed

    private void itemEliminarServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEliminarServiciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemEliminarServiciosActionPerformed

    private void itemEliminarServicios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEliminarServicios1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemEliminarServicios1ActionPerformed

    private void itemEditarServicios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEditarServicios1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemEditarServicios1ActionPerformed

    private void itemBuscarServicioXValor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBuscarServicioXValor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemBuscarServicioXValor1ActionPerformed

    private void itemBuscarServicioXEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBuscarServicioXEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemBuscarServicioXEmailActionPerformed

    private void itemTodosLosUsuarios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTodosLosUsuarios1ActionPerformed
     
            if(Usuario.usuarioBD == null || Usuario.usuarioBD.isEmpty()){
            JOptionPane.showMessageDialog(this, "No existen usuarios registrados"
                   );
        return;
            }
        VentanaReporteUsuarios ventana = new VentanaReporteUsuarios (this,true);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);

    }//GEN-LAST:event_itemTodosLosUsuarios1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuServicios;
    private javax.swing.JMenuBar barramenu;
    private javax.swing.JMenuItem itemAgregarServicios;
    private javax.swing.JMenuItem itemAgregarUsuario;
    private javax.swing.JMenuItem itemBuscarServicioXEmail;
    private javax.swing.JMenuItem itemBuscarServicioXNombre;
    private javax.swing.JMenuItem itemBuscarServicioXValor;
    private javax.swing.JMenuItem itemBuscarServicioXValor1;
    private javax.swing.JMenuItem itemBuscarUsuarioXTelefono;
    private javax.swing.JMenuItem itemConsultarServicios;
    private javax.swing.JMenuItem itemConsultarUsuario;
    private javax.swing.JMenuItem itemEditarServicios;
    private javax.swing.JMenuItem itemEditarServicios1;
    private javax.swing.JMenuItem itemEditarUsuario;
    private javax.swing.JMenuItem itemEliminarServicios;
    private javax.swing.JMenuItem itemEliminarServicios1;
    private javax.swing.JMenuItem itemEliminarUsuario;
    private javax.swing.JMenuItem itemIniciarSesionUsuario;
    private javax.swing.JMenuItem itemTodosLosUsuarios;
    private javax.swing.JMenuItem itemTodosLosUsuarios1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenu menuUsuarios;
    private javax.swing.JMenu subMenuReporteServicios;
    private javax.swing.JMenu subMenuReporteUsuarios;
    // End of variables declaration//GEN-END:variables
}
